# Add application configuration variables here, as shown below.
TWITTER_CONSUMER_KEY: lEXAqdVBeIvSowpZlqHM6Q
TWITTER_CONSUMER_SECRET: k1hkZAuTuCHz7jWD7HZey0Js0ZWYZPgxYrT8VAn8
FOG_DIRECTORY: lbuell
AWS_ACCESS_KEY_ID: AKIAIYSLIYWFJR2QQ6UA
AWS_SECRET_ACCESS_KEY: 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
GMAIL_USERNAME: liamcbuell
GMAIL_PASSWORD: V3rbalexist!
#DEVISE_SECRET: "4552ac3a2cd3c271b0670d768d0aabb9253f8217fc4c6fdf9427b613793f7de34b8df5c53afd0609d60e6e86e6380c34026c1700c7ac13ddcab9fcdbe06cbc0d"
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
